### ISSUE TITLE
Update request an invite text

### ISSUE THREAD

**Issue by iLeonelPerea** [Tinker-Ware/landing-page#23]

**Comment by Att4ck3rS3cur1ty** [comment]
Hey, I want to fix this one. Can you explain in a way better what should I do?

**Comment by iLeonelPerea** [comment]
Hi @Att4ck3rS3cur1ty I wanna:

removeComments
collapseWhitespace
removeRedundantAttributes
useShortDoctype
removeEmptyAttributes
removeStyleLinkTypeAttributes
keepClosingSlash
minifyJS
minifyCSS
minifyURLs
